server {
    listen 80;
    location /api/openings { proxy_pass http://opening-service:8000; }
    location /api/games    { proxy_pass http://game-service:8001; }
    location / { root /usr/share/nginx/html; index index.html; }
}
