services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: chessdb
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspassword
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: